version: '3'

volumes:
        static:
        database:

services:
        classroom_server:
                build:
                        context: .
                        dockerfile: compose/production/django/django_dockerfile
                image: classroom_server
                container_name: classroom_server
                working_dir: /app
                volumes:
                        - database:/app/database
                        - static:/app/nginx_static
                env_file:
                        - .envs/.production
                ports:
                        - "8000:8000"
                command: ./start.sh
        

        nginx:
                build:
                        context: .
                        dockerfile: compose/production/nginx/nginx_dockerfile
                image: classroom_nginx
                container_name: classroom_nginx
                volumes:
                        - static:/static
                ports:
                        - "9090:80"
