# Generated by Django 2.2.6 on 2019-10-11 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom_text', models.CharField(max_length=128, verbose_name='教室')),
                ('camera_ip_text', models.CharField(max_length=128, verbose_name='摄像头IP')),
            ],
        ),
    ]
